[build]
publish = "public"

[build.environment]
HUGO_VERSION = "0.117.0"
HUGO_THEME = "repo"

[context.production]
command = "hugo -b ${URL} --gc -e production"
[context.production.environment]
HUGO_ENV = "production"

[context.branch-deploy]
command = "hugo -b ${DEPLOY_PRIME_URL} --gc -e production"

[context.deploy-preview]
command = "hugo -b ${DEPLOY_PRIME_URL} --gc -e production"

[[plugins]]
package = "netlify-plugin-hugo-cache-resources"

[plugins.inputs]
# If it should show more verbose logs (optional, default = true)
debug = true
