[build]
publish = "public"

[build.environment]
HUGO_VERSION = "0.117.0"
HUGO_THEME = "repo"

[context.production]
command = "tinacms build && hugo -b ${URL}"
[context.production.environment]
HUGO_ENV = "production"

[context.branch-deploy]
command = "tinacms build && hugo -b ${DEPLOY_PRIME_URL}"

[context.deploy-preview]
command = "tinacms build && hugo -b ${DEPLOY_PRIME_URL}"

[[plugins]]
package = "netlify-plugin-hugo-cache-resources"

[plugins.inputs]
# If it should show more verbose logs (optional, default = true)
debug = true
